#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nftables-blacklist"
name = "nftables blacklist"
description.en = "A script to ban large numbers of IP addresses published in blocklists, associated with countries or Autonomous Systems (AS)"
description.fr = "Un script pour bannir de grands nombres d'adresses IP publiées dans des listes de blocage, associées à des pays ou des Systèmes Autonomes (AS)"

version = "2026.08.25~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
code = "https://github.com/trick77/nftables-blacklist"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/trick77/nftables-blacklist/archive/987db647e692b68ccdbf0fb81278e285baa57604.tar.gz"
    sha256 = "c9f65d2c13d96d5101ff87ab028e4c2e8746e27121a45197865ca4c1e306aa6b"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = "curl, iprange"
