#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nftables-blacklist"
name = "nftables blacklist"
description.en = "A script to ban large numbers of IP addresses published in blocklists, associated with countries or Autonomous Systems (AS)"
description.fr = "Un script pour bannir de grands nombres d'adresses IP publiées dans des listes de blocage, associées à des pays ou des Systèmes Autonomes (AS)"

version = "2026.08.27~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
code = "https://github.com/trick77/nftables-blacklist"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/trick77/nftables-blacklist/archive/04a994641f22854310ab55b848490e92d5d4a18d.tar.gz"
    sha256 = "44e753941fd91bcb1f89fa48ad3667a077b99f09d4364b4024fd9bf5b58b8012"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = "curl, iprange"
