# nftables-blacklist configuration
# https://github.com/trick77/nftables-blacklist
#
# See README.md for all available options.
#
# YunoHost's packager comment: do not directly modify this file,
# use the app's configuration panel in the webadmin or the custom txt files.

IP_BLACKLIST=__INSTALL_DIR__/ip-blacklist.list
NFT_BLACKLIST_SCRIPT=__INSTALL_DIR__/blacklist.nft
FORCE=yes

BLACKLISTS=(
__DEFAULT_LIST__

__COUNTRIES_LIST__

__ASN_LIST__

"file://__INSTALL_DIR__/custom_blocklist.txt"
)

AUTO_WHITELIST=yes
WHITELIST=(
__IPS_LIST__

"file://__INSTALL_DIR__/custom_allowlist.txt"
)

ENABLE_IPV4=yes
ENABLE_IPV6=yes
NFT_TABLE_NAME=blacklist
NFT_SET_NAME_V4=blacklist4
NFT_SET_NAME_V6=blacklist6
NFT_CHAIN_PRIORITY=-200
BLOCK_FORWARD=__BLOCK_FORWARD__
CHUNK_SIZE=5000
CURL_CONNECT_TIMEOUT=10
CURL_MAX_TIME=30
