#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/$app-update.service"
ynh_backup "/etc/systemd/system/$app-update.timer"

ynh_backup "/etc/logrotate.d/$app"
ynh_backup "/etc/sudoers.d/$app"

# NB: /var/log is not backuped during safety-backup-before-upgrades, same as $data_dir
ynh_backup "/var/log/$app/"

cat "$install_dir/nftables-blacklist.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
