#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# DEFAULTS
#=================================================

if [ "$use_default_blocklists" = "yes" ]; then
    # Taken from https://github.com/trick77/nftables-blacklist/blob/master/nftables-blacklist.conf#L30-L59
    default_list='"https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1" "http://danger.rulez.sk/projects/bruteforceblocker/blist.php" "https://www.spamhaus.org/drop/drop_v4.json" "https://www.spamhaus.org/drop/drop_v6.json" "https://cinsscore.com/list/ci-badguys.txt" "https://lists.blocklist.de/lists/all.txt" "https://blocklist.greensnow.co/greensnow.txt"  "https://iplists.firehol.org/files/firehol_level1.netset" "https://iplists.firehol.org/files/stopforumspam_7d.ipset" "https://rules.emergingthreats.net/blockrules/compromised-ips.txt"'
else
    default_list=''
fi

# Unfortunately YunoHost relies on external infrastructure
# Blocking some AS can pretty much prevent updates and app installations.
# The AS are found thanks to https://lens.ipverse.net/
yunohost_protected_asn=(
    # Google ASN hosts the Go language
    15169
    # GitHub hosts all YunoHost apps
    36459
)

#=================================================
# HANDLING THE VARIABLES
#=================================================

# Convert the comma-separated list of tags into arrays
IFS=',' read -r -a countries_array  <<< "${countries:=}"
IFS=',' read -r -a asn_array        <<< "${asn:=}"
IFS=',' read -r -a ips_array        <<< "${ips:=}"

# Initialize the lists that will be put in the configuration file
countries_list=""
asn_list=""
ips_list=""

# For each country code, we append the IPv4 and IPv6 list URLs
for country in "${countries_array[@]}"; do
    # let's force lower case country codes
    cc=$(printf '%s' "$country" | tr '[:upper:]' '[:lower:]')

    countries_list+=" \"https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/${cc}/ipv4-aggregated.txt\" \"https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/${cc}/ipv6-aggregated.txt\""
done

# For each AS, we add the IPv4 and IPv6 lists...
for as in "${asn_array[@]}"; do
    # ...but before that we check that the AS is not in the list of protected AS
    # the Bash expansion black magic returns _found_ if the AS is found in the array, nothing if not found
    # the -z test makes sure we proceed if nothing is found
    if [[ -z ${yunohost_protected_asn[$as]+_found_} ]]; then
        asn_list+=" \"https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/${as}/ipv4-aggregated.txt\" \"https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/${as}/ipv6-aggregated.txt\""
    fi
done

# We surround each IP with double quotes
for ip in "${ips_array[@]}"; do
    ips_list+=" \"${ip}\""
done

ynh_app_setting_set --key=countries --value="${countries}"
ynh_app_setting_set --key=asn       --value="${asn}"
ynh_app_setting_set --key=ips       --value="${ips}"

ynh_config_add --template="nftables-blacklist.conf" --destination="$install_dir/nftables-blacklist.conf"

# Make sure the custom files exist
if [[ ! -s "$install_dir/custom_allowlist.txt" ]]; then
    ynh_script_progression "Fixing up allow list..."
    echo "# Add custom allow listed IPs below" > "$install_dir/custom_allowlist.txt"
    chown "$app:$app" "$install_dir/custom_allowlist.txt"
fi

if [[ ! -s "$install_dir/custom_blocklist.txt" ]]; then
    ynh_script_progression "Fixing up block list..."
    printf "# Add custom block listed IPs below\n# Prefilled 203.0.113.1 is a reserved IP that matches nothing in real world\n203.0.113.1" > "$install_dir/custom_blocklist.txt"
    chown "$app:$app" "$install_dir/custom_blocklist.txt"
fi

ynh_systemctl --service="$app" --action="start"

#=================================================
ynh_app_config_run "$1"
