#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key=use_default_blocklists --value=0
ynh_app_setting_set_default --key=default_list           --value='"https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1" "http://danger.rulez.sk/projects/bruteforceblocker/blist.php" "https://www.spamhaus.org/drop/drop_v4.json" "https://www.spamhaus.org/drop/drop_v6.json" "https://cinsscore.com/list/ci-badguys.txt" "https://lists.blocklist.de/lists/all.txt" "https://blocklist.greensnow.co/greensnow.txt"  "https://iplists.firehol.org/files/firehol_level1.netset" "https://iplists.firehol.org/files/stopforumspam_7d.ipset" "https://rules.emergingthreats.net/blockrules/compromised-ips.txt"'
ynh_app_setting_set_default --key=countries_list         --value=""
ynh_app_setting_set_default --key=asn_list               --value=""
ynh_app_setting_set_default --key=ips_list               --value=""
ynh_app_setting_set_default --key=block_forward          --value="no"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="nftables-blacklist.conf" --destination="$install_dir/nftables-blacklist.conf"

chmod 500 "$install_dir/update-blacklist.sh"

chmod 600 "$install_dir/nftables-blacklist.conf"
chown "$app:$app" "$install_dir/nftables-blacklist.conf"

echo "# Add custom allow listed IPs below" > "$install_dir/custom_allowlist.txt"
echo "# Add custom block listed IPs below" > "$install_dir/custom_blocklist.txt"
chown "$app:$app" "$install_dir/custom_allowlist.txt"
chown "$app:$app" "$install_dir/custom_blocklist.txt"

mkdir -p "/var/log/$app"
chown "$app:$app" -R "/var/log/$app"

ynh_config_add --template="sudoers" --destination="/etc/sudoers.d/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd
yunohost service add "$app" --description="nftables blacklist" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.service"

# Update service and timer
ynh_config_add --template="systemd-update.service" --destination="/etc/systemd/system/$app-update.service"
ynh_config_add --template="systemd-update.timer" --destination="/etc/systemd/system/$app-update.timer"

systemctl daemon-reload
systemctl enable "$app-update.timer" --now --quiet

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
