#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_config_remove_systemd

ynh_safe_rm "/etc/systemd/system/$app-update.service"
ynh_safe_rm "/etc/systemd/system/$app-update.timer"
ynh_safe_rm "/etc/sudoers.d/$app"

systemctl disable "$app-update.timer" --now --quiet
systemctl daemon-reload

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
