#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

ynh_restore "/etc/systemd/system/$app-update.service"
systemctl enable "$app-update.service" --quiet

ynh_restore "/etc/systemd/system/$app-update.timer"
systemctl enable "$app-update.timer" --now --quiet

yunohost service add "$app" --description="nftables blacklist" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.service"

ynh_restore "/etc/logrotate.d/$app"
ynh_restore "/etc/sudoers.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD THE APP SERVICE
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
