#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

systemctl stop "$app-update.timer" --quiet

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=use_default_blocklists --value="no"
ynh_app_setting_set_default --key=default_list           --value=""
ynh_app_setting_set_default --key=countries_list         --value=""
ynh_app_setting_set_default --key=asn_list               --value=""
ynh_app_setting_set_default --key=ips_list               --value=""
ynh_app_setting_set_default --key=block_forward          --value="no"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="nftables-blacklist.conf"

chown -R "$app:$app" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="nftables-blacklist.conf" --destination="$install_dir/nftables-blacklist.conf"

chmod 500 "$install_dir/update-blacklist.sh"

chmod 600 "$install_dir/nftables-blacklist.conf"
chown "$app:$app" "$install_dir/nftables-blacklist.conf"

if [[ ! -s "$install_dir/custom_allowlist.txt" ]]; then
    ynh_script_progression "Fixing up allow list..."
    echo "# Add custom allow listed IPs below" > "$install_dir/custom_allowlist.txt"
    chown "$app:$app" "$install_dir/custom_allowlist.txt"
fi

if [[ ! -s "$install_dir/custom_blocklist.txt" ]]; then
    ynh_script_progression "Fixing up block list..."
    printf "# Add custom block listed IPs below\n# Prefilled 203.0.113.1 is a reserved IP that matches nothing in real world\n203.0.113.1" > "$install_dir/custom_blocklist.txt"
    chown "$app:$app" "$install_dir/custom_blocklist.txt"
fi

ynh_config_add --template="sudoers" --destination="/etc/sudoers.d/$app"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_systemd
yunohost service add "$app" --description="nftables blacklist" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.service"

# Update service and timer
ynh_config_add --template="systemd-update.service" --destination="/etc/systemd/system/$app-update.service"
ynh_config_add --template="systemd-update.timer" --destination="/etc/systemd/system/$app-update.timer"

systemctl daemon-reload
systemctl enable "$app-update.timer" --now --quiet

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
